version: '3'

services:
  site: 
    image: jekyll/jekyll:latest
    container_name: blog
    volumes:
        - ./:/srv/jekyll
    environment:
        - JEKYLL_ENV=docker
    # force_polling makes the linux box watch for any changes to files, then it will regenerate
    # livereload gets the browser to automatically refresh when changes happen to files
    # command: jekyll serve --force_polling --livereload --watch --verbose
    command: jekyll serve --watch --verbose
    ports:
        - 4000:4000
        - 35729:35729
